# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Addlayout.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!
import datetime


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5 import QtSql
from PyQt5.QtSql import QSqlQuery

from sqlalchemy import create_engine, MetaData
from sqlalchemy.sql import select
from sqlalchemy import Table, Column, Date, Integer, String, ForeignKey
from sqlalchemy.orm import sessionmaker

from DB import Customer


class Ui_CustomerPage(object):
    def setupUi(self, CustomerPage):
        CustomerPage.setObjectName("CustomerPage")
        CustomerPage.resize(700, 500)
        CustomerPage.setMaximumSize(QtCore.QSize(700, 500))
        self.centralwidget = QtWidgets.QWidget(CustomerPage)
        self.centralwidget.setGeometry(QtCore.QRect(0, 0, 700, 500))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.statusbar = QtWidgets.QStatusBar(CustomerPage)
        self.statusbar.setGeometry(QtCore.QRect(0, 0, 3, 18))
        self.statusbar.setObjectName("statusbar")
        self.frame = QtWidgets.QFrame(CustomerPage)
        self.frame.setGeometry(QtCore.QRect(0, 10, 704, 500))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setMinimumSize(QtCore.QSize(80, 0))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_13.addWidget(self.label_18)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.horizontalLayout_13.addWidget(self.lineEdit_17)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_13.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_13.addWidget(self.pushButton_5)
        self.gridLayout_4.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setMinimumSize(QtCore.QSize(80, 0))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_7.addWidget(self.label_17)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.horizontalLayout_7.addWidget(self.lineEdit_13)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setMinimumSize(QtCore.QSize(84, 0))
        self.label_13.setMaximumSize(QtCore.QSize(84, 16777215))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_14.addWidget(self.label_13)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_14.setMaximumSize(QtCore.QSize(400, 16777215))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.horizontalLayout_14.addWidget(self.lineEdit_14)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setMinimumSize(QtCore.QSize(84, 0))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_6.addWidget(self.lineEdit_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setMinimumSize(QtCore.QSize(84, 0))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setMaximumSize(QtCore.QSize(400, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setMinimumSize(QtCore.QSize(84, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(400, 16777215))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setMinimumSize(QtCore.QSize(84, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(400, 16777215))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setMinimumSize(QtCore.QSize(84, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_5.addWidget(self.lineEdit_5)
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_12.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_5.addWidget(self.lineEdit_12)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_15.setMaximumSize(QtCore.QSize(400, 16777215))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.horizontalLayout_15.addWidget(self.lineEdit_15)
        self.gridLayout_3.addLayout(self.horizontalLayout_15, 1, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setMinimumSize(QtCore.QSize(80, 0))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_8.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_8.sizePolicy().hasHeightForWidth())
        self.lineEdit_8.setSizePolicy(sizePolicy)
        self.lineEdit_8.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_9.addWidget(self.lineEdit_8)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_9.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_9.addWidget(self.lineEdit_9)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 3, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setMinimumSize(QtCore.QSize(80, 0))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_10.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_10.sizePolicy().hasHeightForWidth())
        self.lineEdit_10.setSizePolicy(sizePolicy)
        self.lineEdit_10.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_10.addWidget(self.lineEdit_10)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_11.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_11.setText("")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_10.addWidget(self.lineEdit_11)
        self.gridLayout_3.addLayout(self.horizontalLayout_10, 4, 0, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_19.addWidget(self.label_19)
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout_19.addWidget(self.comboBox_3)
        self.gridLayout_3.addLayout(self.horizontalLayout_19, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setMinimumSize(QtCore.QSize(66, 0))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_7.setMaximumSize(QtCore.QSize(400, 16777215))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_8.addWidget(self.lineEdit_7)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 2, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_3)
        self.gridLayout_6.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(670, 350))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setMinimumSize(QtCore.QSize(0, 15))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame_3)
        self.textEdit_2.setMaximumSize(QtCore.QSize(500, 100))
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_2.addWidget(self.textEdit_2)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_16 = QtWidgets.QLabel(self.frame_3)
        self.label_16.setMinimumSize(QtCore.QSize(120, 0))
        self.label_16.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_16.addWidget(self.label_16)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_16.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.horizontalLayout_16.addWidget(self.lineEdit_16)
        self.gridLayout_5.addLayout(self.horizontalLayout_16, 1, 0, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_21 = QtWidgets.QLabel(self.frame_3)
        self.label_21.setMinimumSize(QtCore.QSize(120, 0))
        self.label_21.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_17.addWidget(self.label_21)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_20.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.horizontalLayout_17.addWidget(self.lineEdit_20)
        self.gridLayout_5.addLayout(self.horizontalLayout_17, 2, 0, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_22 = QtWidgets.QLabel(self.frame_3)
        self.label_22.setMinimumSize(QtCore.QSize(120, 0))
        self.label_22.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_18.addWidget(self.label_22)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_21.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.horizontalLayout_18.addWidget(self.lineEdit_21)
        self.gridLayout_5.addLayout(self.horizontalLayout_18, 3, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 2, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame_3, 2, 0, 1, 1)

        self.retranslateUi(CustomerPage)
        QtCore.QMetaObject.connectSlotsByName(CustomerPage)

    def retranslateUi(self, CustomerPage):
        _translate = QtCore.QCoreApplication.translate
        CustomerPage.setWindowTitle(_translate("CustomerPage", "MainWindow"))
        self.label_18.setText(_translate("CustomerPage", "Lookup: "))
        self.pushButton_4.setText(_translate("CustomerPage", "Find"))
        self.pushButton_5.setText(_translate("CustomerPage", "Print"))
        self.label_17.setText(_translate("CustomerPage", "* Customer ID:"))
        self.label_13.setText(_translate("CustomerPage", "Market Group:"))
        self.label_6.setText(_translate("CustomerPage", "Company Name:"))
        self.label.setText(_translate("CustomerPage", "Address 1:"))
        self.label_2.setText(_translate("CustomerPage", "Address 2:"))
        self.label_3.setText(_translate("CustomerPage", "Address 3:"))
        self.label_5.setText(_translate("CustomerPage", "City:"))
        self.label_12.setText(_translate("CustomerPage", "Postcode"))
        self.label_15.setText(_translate("CustomerPage", "First Name:"))
        self.label_8.setText(_translate("CustomerPage", "Phone Number:"))
        self.label_9.setText(_translate("CustomerPage", "Fax Number:"))
        self.label_19.setText(_translate("CustomerPage", "Title: "))
        self.comboBox_3.setItemText(0, _translate("CustomerPage", "Mrs"))
        self.comboBox_3.setItemText(1, _translate("CustomerPage", "Ms."))
        self.comboBox_3.setItemText(2, _translate("CustomerPage", "Mr."))
        self.label_7.setText(_translate("CustomerPage", "Last Name:"))
        self.label_14.setText(_translate("CustomerPage", "Residential Delivery Intruction/Notes:"))
        self.textEdit_2.setHtml(_translate("CustomerPage", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">312222222222222222222222222222222222222222222222222222222222222222222222222222222312222222222222222222222222222222222222222222222222222222222222222222222222222222312222222222222222222222222222222222222222222222222222222222222222222222222222222312222222222222222222222222222222222222222222222222222222222222222222222222222222</p></body></html>"))
        self.label_16.setText(_translate("CustomerPage", "Email Address 1:"))
        self.label_21.setText(_translate("CustomerPage", "Email Address 2:"))
        self.label_22.setText(_translate("CustomerPage", "Email Address 3:"))
        self.pushButton.setText(_translate("CustomerPage", "Delete Customer"))
        self.pushButton_2.setText(_translate("CustomerPage", "Save Customer"))
        self.pushButton_3.setText(_translate("CustomerPage", "Add Another"))
        self.pushButton_2.clicked.connect(self.login)
        self.pushButton_3.clicked.connect(self.check)

        # @QtCore.pyqtSlot()

    def login(self):
        print(self.lineEdit_15.text())

        # query = QSqlQuery()
        #
        # query.exec_("insert into person values(1, 'Bauer', 'beijing')")
        # query.exec_("insert into person values(2, 'Jack', 'shanghai')")
        # query.exec_("insert into person values(3, 'Alex', 'chengdu')")
        # query.exec_("insert into person values(6, 'Bauer', 'beijing')")
        # query.exec_("insert into person values(9, 'Jack', 'shanghai')")
        # query.exec_("insert into person values(8, 'Alex', 'chengdu')")
        #
        # query.prepare('select * from person')
        # if not query.exec_():
        #     query.lastError()
        #     print('not exec')
        # else:
        #     while query.next():
        #         id = query.value(0)
        #         name = query.value(1)
        #         address = query.value(2)
        #         print(id, name, address)
        engine = create_engine('sqlite:///test2.db', echo=True)
        metadata = MetaData(engine)
        # Session = sessionmaker(bind=engine)
        customer_table = Table('customer', metadata, autoload=True)
        print(customer_table)
        ins = customer_table.insert()

        print(ins)
        # session = Session()
        ts = datetime.datetime.now().timestamp()
        ins = ins.values(id='20200101', company_name='xiaoming', address_one='Li XiaoMing', create_date=ts)

        conn = engine.connect()
        conn.execute(customer_table.insert(), [
            {'id': '2019', 'company_name': 'bob', },
            {'id': '2018', 'company_name': 'alice'},
        ])
        # # 执行语句
        print('inserted')
        result = conn.execute(ins)

    def check(self):
        # query = QSqlQuery()
        # query.prepare('select * from person')
        # if not query.exec_():
        #     query.lastError()
        #     print('not exec')
        # else:
        #     while query.next():
        #         id = query.value(0)
        #         name = query.value(1)
        #         address = query.value(2)
        #         print(id, name, address)

        engine = create_engine('sqlite:///test2.db', echo=False)
        metadata = MetaData(engine)
        Session = sessionmaker(bind=engine)
        session = Session()
        for each_customer in session.query(Customer):
            print('current id is:')
            print(each_customer)


    def add_more(self):
        pass

    def delete(self):
        pass

    def save(self):
        pass

    def print(self):
        pass

    def lookup(self):
        pass
